### ISSUE TITLE
1.19.4 Crystal Laser Error

### ISSUE THREAD

**Issue by Nesanco** [SkytAsul/GuardianBeam#21]
whenever i target a crystal laser over 1 tick i get kicked and get this error:
https://pastebin.com/dviciLmf

1.19.4

    public void target(Location location, int time, @Nullable BukkitRunnable callback) {
        laser.moveEnd(location, time, callback);
    }

**Comment by SkytAsul** [comment]
Is this still a thing?

**Comment by Nesanco** [comment]
sorry for the late response, but yes

**Comment by SkytAsul** [comment]
What is your server software?

**Comment by Nesanco** [comment]
Pufferfish+
1.19.4
Java 17

**Comment by SkytAsul** [comment]
Could you try with a basic Paper server if the problem is still there?

**Comment by Nesanco** [comment]
same issue, paper 1.19.4, same everything else

**Comment by SkytAsul** [comment]
I'll investigate this.

**Comment by SkytAsul** [comment]
Are you maybe trying to set the same end position as the one previously set?

**Comment by Nesanco** [comment]
no, i create the beam at 0, 0, 0 for example, then just target it to 10, 10, 10 for example, and get the error, i cant really send the code since the player does the locations and stuff

**Comment by SkytAsul** [comment]
Alright well I cannot replicate... do you have ProtocolLib installed on your server?

**Comment by Nesanco** [comment]
sorry for the late response but yes

**Comment by SkytAsul** [comment]
Can you retry without ProtocolLib?

**Comment by Nesanco** [comment]
i have tried it with and without, same issue

**Comment by SkytAsul** [comment]
Okay, can you try to create a dumb laser with start position being 0 0 0 and end position 10 10 10, start it and see if it works?

**Comment by Nesanco** [comment]
by end position do you mean it moving to 10, 10, 10? also i assume you mean crystal laser?

**Comment by SkytAsul** [comment]
No, put the end location to 10 10 10 at creation, and then make it move somewhere else _instantly_ using moveEnd(location)

**Comment by Nesanco** [comment]
same error using
```        World world = Bukkit.getWorld("world");
        try {
            Laser.CrystalLaser beam = new Laser.CrystalLaser(new Location(world, 0, 0, 0), new Location(world, 10, 10, 10), -1, 40);
            beam.start(Core.getPlugin());
            beam.moveEnd(new Location(world, 20, 20, 20), 80, null);
        } catch (ReflectiveOperationException ex) {
            throw new RuntimeException(ex);
        }
```
https://pastebin.com/QDUvtvb6

**Comment by SkytAsul** [comment]
Try to delay the "moveEnd" thing by 5 seconds using a scheduler, and tell me if you get kicked after the "start" or after the "moveEnd" (or not at all if waiting before moveEnd fixes the problem)

**Comment by Nesanco** [comment]
i get kicked after the moveEnd

**Comment by SkytAsul** [comment]
And does it happen with a Guardian laser instead of a Crystal one? (sorry for all those questions but as I can't reproduce the bug I must ask those :sweat_smile:)

**Comment by Nesanco** [comment]
it is just the crystal laser

**Comment by stijnb1234** [comment]
+1, still happening (on 1.20.2 too)

**Comment by stijnb1234** [comment]
```
[20:36:04 ERROR]: Packet encoding of packet ID 84 threw (skippable? false)
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "trackedValues" is null
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.pack(ClientboundSetEntityDataPacket.java:17) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:38) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:42) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.20.2.jar:git-Paper-243]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
	at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by SkytAsul** [comment]
Seems like both of you are using ProtocolLib, that's weird. Could you try without?

**Comment by stijnb1234** [comment]
> Seems like both of you are using ProtocolLib, that's weird. Could you try without?

Not related, without ProtocolLib I get a similar error:
```
[11:09:00 ERROR]: Packet encoding of packet ID 84 threw (skippable? false)
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "trackedValues" is null
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.pack(ClientboundSetEntityDataPacket.java:17) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:38) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:42) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.20.2.jar:git-Paper-243]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
	at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:09:01 INFO]: SBDeveloper lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "trackedValues" is null
```

**Comment by stijnb1234** [comment]
Maybe this is related (seems to contain the same error message):
- https://www.spigotmc.org/threads/applying-per-player-name-tags-to-entities-using-nms-1-19-3.582896/
- https://forums.papermc.io/threads/error-when-more-than-one-player.689/

**Comment by SkytAsul** [comment]
Thanks for the search, but it does not seem related to the same problem.
Does it happen when you're alone in the server or only when there are multiple players nearby?

**Comment by stijnb1234** [comment]
Directly when I join the server I get _kicked._

11 nov. 2023 11:07:25 SkytAsul ***@***.***>:

**Comment by SkytAsul** [comment]
??? The problem was said to happen only when the laser was moving?

**Comment by stijnb1234** [comment]
Then this seems unrelated. When I join a server with a crystal laser in it, I directly get _kicked._

11 nov. 2023 21:18:05 SkytAsul ***@***.***>:

**Comment by SkytAsul** [comment]
I can't reproduce, neither on 1.19.4 nor 1.20.2. The error is too vague to allow me to understand what is happening and how shall I fix that.
I _need_ to be able to reproduce, so please send me both a list of all your plugins. Also please tell me if you are running a proxy server such as BungeeCord.

**Comment by stijnb1234** [comment]
To reproduce, follow these steps:
1. Download [this server file](https://sbdevelopment.tech/Server-1.20.2-GuardianBeam.zip).
2. Start the server.
3. Join the server using Minecraft 1.20.2.
4. Give yourself OP in the console.
5. Execute the commands `/sc create test` and `/sc add test 0s spot test <Your location>` *(Replace `<Your location>` by your current location, the plugin will also tab complete this!)*
6. Get kicked, with the error message in the console.

This PaperSpigot 1.20.2 server (no server settings changed!) only contains my plugin ShowControl, which uses GuardianBeam for the `spot`. See [this class](https://github.com/SBDPlugins/ShowControl/blob/master/src/main/java/tech/sbdevelopment/showcontrol/elements/Lasers.java) for how I use it.

**Comment by SkytAsul** [comment]
Thanks! I finally understand what is going on: this is because you are moving the crystal multiple times to the same location. I will fix that.

**Comment by SkytAsul** [comment]
Could you try again with 2.3.5?

**Comment by stijnb1234** [comment]
> Could you try again with 2.3.5?

Fixed it, thanks!

**Comment by Nesanco** [comment]
(still having the original issue with version 2.3.5)

when targeting a crystal laser over 100 ticks I get kicked and get this error
https://pastebin.com/N1C5czNk

this is only with the crystal laser and when targeting a crystal laser over 20 ticks or 1 tick I don't get kicked or anything

**Comment by SkytAsul** [comment]
Can you open another issue with more informations on how to reproduce? With code if possible.
